### PR TITLE
Api path changes

### PR DESCRIPTION
**Pull request by belldandu**

### CODE REVIEW

**Comment by TheLastRar** [comment]
Sorry for the delay, was on holiday.

Few Notes

This change needs to be applied DownloadFile() (API.cs), note that this may run into issues with lobby Chat.

This change will need to be applied to LobbyURL() ( LobbyServerChecker/AreaServerChecker/LobbyTracker.cs) as it is used to open the status page from the context menu. however, this function is also called to get the URL for lobby chat, which (unless this is also changed) will need to use the port.

Does the default URL need to be changed (https://github.com/belldandu/LobbyServerChecker/blob/a5799adb48f94eea8376d84a8aca6839f2bd97d4/AreaServerChecker/MainForm.cs#L92)
Note the check bellow this line, which assumed https wasn't used (hopefully that would be all that is needed for https support).
The chat currently uses the same URL as the lobby api calls (since this was the case with the old paths). if this is no-longer the case, code changes will need to be done to reflect this.

**Comment by belldandu** [comment]
Lobby api calls are now done from https://fragment.coldbird.net/api/lobby.xml
Where as the chat should connect from http://fragment.coldbird.net:49000

You are no longer able to or allowed to get the status page information from the port. Mostly because we are trying to reduce the amount of stress on the lobby.

So yes code changes need to be done to reflect this.

**Comment by TheLastRar** [comment]
OK

Is there still need to be able to specify custom lobbies in lobbies.txt?

You where the one who originally requested this feature and the current system will need to be modified/replaced to support the different URLs.

**Comment by belldandu** [comment]
Yep

**Comment by belldandu** [comment]
although @TheLastRar you should change it to be a yml file so that people can specify the port for the chat to connect to.

**Comment by belldandu** [comment]
```- www.coldbird.net
    - 49000
```
etc.

**Comment by belldandu** [comment]
gonna keep this open for now as notes
will close once everything is done.

**Comment by TheLastRar** [comment]
Notes on YAML

I heard it was rather picky with indents.
The example you posted is not valid yml
.Net does not provide a yml, needing either a dependency or roll my own implementation (which will likely be even more picky with indents and might reject otherwise valid files)

**Comment by belldandu** [comment]
Yeah

How do you feel about just splitting on a comma in the text file
```
fragment.coldbird.net,49000
```
for now.

**Comment by belldandu** [comment]
It looks like this has been finished so imma close this.

**Pull request closed without merging**
